### ISSUE TITLE
Project CMS

### ISSUE THREAD

**Issue by michela** [Indigemoji-Australia/indigemoji-app#24]
Migrate master images and copy to CMS to faciliate editorial workflow and address #12, #17 #21  

Using open source web CMS Wagtail
https://wagtail.io/

Aims:
* Retrofit all app page templates into CMS so any future Arrernte or other community apps can be managed more efficiently.
 * Staging of pre-release content for editorial review
 * Automating and streamlining updates
 * Scope for managing multiple sticker sets (e.g. for different communities)
 
Process
* Draft Information Architecture (IA)  
* Draft page templates f 
 * e.g. 
 * Help text screens
  * Emoji index
  * Emoji page
  * About
  * FAQ
  * Team
* Create hosted CMS instance (on Rack&Pin)
* Create user accounts for editorial content management access
* Transfer master image, audio and text into CMS

**Comment by michela** [comment]
Task complete apart from 

>Transfer master image, audio and text into CMS

See HOWTO video and credentials provided

**Comment by CaddieBrain** [comment]
Master image, audio and text transferred.
